apiVersion: v1
kind: Namespace
metadata:
  name: seq

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq
  namespace: seq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seq
  template:
    metadata:
      labels:
        app: seq
    spec:
      containers:
        - name: seq
          image: datalust/seq:latest
          ports:
            - containerPort: 80
          env:
            - name: ACCEPT_EULA
              value: "Y"
          volumeMounts:
            - name: seq-data
              mountPath: /data
      volumes:
        - name: seq-data
          hostPath:
            path: /opt/seq
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: seq-service
  namespace: seq
  labels:
    app: seq
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: seq-hetzner
spec:
  selector:
    app: seq
  type: ClusterIP
  ports:
    - port: 5341
      targetPort: 80
      name: web